version: "2"
services:
  app:
    build: .
    image: karolguimaraes/bravo:1.0
    ports: 
      - "8000:8000"
    volumes:
      - ./bravo:/bravo
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"